"""Agregar rol a usuarios

Revision ID: 62060ea69d63
Revises: 8444ff60bb86
Create Date: 2026-09-03 23:30:03.365580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62060ea69d63'
down_revision: Union[str, Sequence[str], None] = '8444ff60bb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rol', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###
