"""crear permisos y rol permisos

Revision ID: c29895b2adbc
Revises: 62060ea69d63
Create Date: 2026-09-05 11:14:10.286861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29895b2adbc'
down_revision: Union[str, Sequence[str], None] = '62060ea69d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_permisos_id'), 'rol_permisos', ['id'], unique=False)
    op.create_index(op.f('ix_rol_permisos_rol'), 'rol_permisos', ['rol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_permisos_rol'), table_name='rol_permisos')
    op.drop_index(op.f('ix_rol_permisos_id'), table_name='rol_permisos')
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
