"""Crear carritos y detalles

Revision ID: e64abf9020c7
Revises: c74eb7ac7a09
Create Date: 2026-09-03 12:25:02.607282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64abf9020c7'
down_revision: Union[str, Sequence[str], None] = 'c74eb7ac7a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carritos_id'), 'carritos', ['id'], unique=False)
    op.create_table('detalles_carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_carrito_id'), 'detalles_carrito', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_carrito_id'), table_name='detalles_carrito')
    op.drop_table('detalles_carrito')
    op.drop_index(op.f('ix_carritos_id'), table_name='carritos')
    op.drop_table('carritos')
    # ### end Alembic commands ###
